# Test your FastAPI endpoints
GET http://127.0.0.1:8000/status
Accept: "application/json"
###
GET http://127.0.0.1:8000/tree/text/0
Accept: "application/json"
###
GET http://127.0.0.1:8000/tree/text/1
Accept: "application/json"
###
GET http://127.0.0.1:8000/tree/image_graphviz/0
Accept: "application/json"
###
GET http://127.0.0.1:8000/tree/image_graphviz/1
Accept: "application/json"
###
GET http://127.0.0.1:8000/tree/image_igraph/0
Accept: "application/json"
###
GET http://127.0.0.1:8000/tree/image_igraph/1
Accept: "application/json"